version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: job_postgres
    environment:
      POSTGRES_USER: job_user
      POSTGRES_PASSWORD: job_password
      POSTGRES_DB: job_db
    ports:
      - "5432:5432"
    volumes:
      - job_pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  job_pg_data:
